package app.saadiah.model

import kotlinx.datetime.TimeZone

/**
 * Curated list of prominent cities spanning every standard timezone offset from UTC-10 to UTC+13.
 * These provide quick zero-keystroke selection and serve as global benchmark targets.
 */
val EXTENDED_CITIES: List<City> =
    listOf(
        City(
            id = CityId(5856195),
            name = "Honolulu",
            country = CountryCode("US"),
            admin1 = "Hawaii",
            coordinates = Coordinates(21.3069, -157.8583),
            timeZone = TimeZone.of("Pacific/Honolulu"),
        ),
        City(
            id = CityId(5879400),
            name = "Anchorage",
            country = CountryCode("US"),
            admin1 = "Alaska",
            coordinates = Coordinates(61.2181, -149.9003),
            timeZone = TimeZone.of("America/Anchorage"),
        ),
        City(
            id = CityId(5368361),
            name = "Los Angeles",
            country = CountryCode("US"),
            admin1 = "California",
            coordinates = Coordinates(34.0522, -118.2437),
            timeZone = TimeZone.of("America/Los_Angeles"),
        ),
        City(
            id = CityId(5419384),
            name = "Denver",
            country = CountryCode("US"),
            admin1 = "Colorado",
            coordinates = Coordinates(39.7392, -104.9847),
            timeZone = TimeZone.of("America/Denver"),
        ),
        City(
            id = CityId(4887398),
            name = "Chicago",
            country = CountryCode("US"),
            admin1 = "Illinois",
            coordinates = Coordinates(41.8500, -87.6500),
            timeZone = TimeZone.of("America/Chicago"),
        ),
        City(
            id = CityId(5128581),
            name = "New York City",
            country = CountryCode("US"),
            admin1 = "New York",
            coordinates = Coordinates(40.7143, -74.0060),
            timeZone = TimeZone.of("America/New_York"),
        ),
        City(
            id = CityId(6324729),
            name = "Halifax",
            country = CountryCode("CA"),
            admin1 = "Nova Scotia",
            coordinates = Coordinates(44.6427, -63.5769),
            timeZone = TimeZone.of("America/Halifax"),
        ),
        City(
            id = CityId(3448439),
            name = "São Paulo",
            country = CountryCode("BR"),
            admin1 = "São Paulo",
            coordinates = Coordinates(-23.5475, -46.6361),
            timeZone = TimeZone.of("America/Sao_Paulo"),
        ),
        City(
            id = CityId(3385075),
            name = "Fernando de Noronha",
            country = CountryCode("BR"),
            admin1 = "Pernambuco",
            coordinates = Coordinates(-3.8546, -32.4277),
            timeZone = TimeZone.of("America/Noronha"),
        ),
        City(
            id = CityId(3374333),
            name = "Praia",
            country = CountryCode("CV"),
            admin1 = "Praia",
            coordinates = Coordinates(14.9315, -23.5125),
            timeZone = TimeZone.of("Atlantic/Cape_Verde"),
        ),
        City(
            id = CityId(2253354),
            name = "Dakar",
            country = CountryCode("SN"),
            admin1 = "Dakar",
            coordinates = Coordinates(14.6937, -17.4441),
            timeZone = TimeZone.of("Africa/Dakar"),
        ),
        City(
            id = CityId(2643743),
            name = "London",
            country = CountryCode("GB"),
            admin1 = "England",
            coordinates = Coordinates(51.5085, -0.1257),
            timeZone = TimeZone.of("Europe/London"),
        ),
        City(
            id = CityId(2332459),
            name = "Lagos",
            country = CountryCode("NG"),
            admin1 = "Lagos",
            coordinates = Coordinates(6.4541, 3.3947),
            timeZone = TimeZone.of("Africa/Lagos"),
        ),
        City(
            id = CityId(360630),
            name = "Cairo",
            country = CountryCode("EG"),
            admin1 = "Cairo",
            coordinates = Coordinates(30.0626, 31.2497),
            timeZone = TimeZone.of("Africa/Cairo"),
        ),
        City(
            id = CityId(993800),
            name = "Johannesburg",
            country = CountryCode("ZA"),
            admin1 = "Gauteng",
            coordinates = Coordinates(-26.2023, 28.0436),
            timeZone = TimeZone.of("Africa/Johannesburg"),
        ),
        City(
            id = CityId(104515),
            name = "Makkah",
            country = CountryCode("SA"),
            admin1 = "Mecca Region",
            coordinates = Coordinates(21.42664, 39.82563),
            timeZone = TimeZone.of("Asia/Riyadh"),
            arabicName = "مكة المكرمة",
        ),
        City(
            id = CityId(112931),
            name = "Tehran",
            country = CountryCode("IR"),
            admin1 = "Tehran",
            coordinates = Coordinates(35.6944, 51.4215),
            timeZone = TimeZone.of("Asia/Tehran"),
        ),
        City(
            id = CityId(292223),
            name = "Dubai",
            country = CountryCode("AE"),
            admin1 = "Dubai",
            coordinates = Coordinates(25.0772, 55.3093),
            timeZone = TimeZone.of("Asia/Dubai"),
        ),
        City(
            id = CityId(1138958),
            name = "Kabul",
            country = CountryCode("AF"),
            admin1 = "Kabul",
            coordinates = Coordinates(34.5281, 69.1723),
            timeZone = TimeZone.of("Asia/Kabul"),
        ),
        City(
            id = CityId(1174872),
            name = "Karachi",
            country = CountryCode("PK"),
            admin1 = "Sindh",
            coordinates = Coordinates(24.8608, 67.0104),
            timeZone = TimeZone.of("Asia/Karachi"),
        ),
        City(
            id = CityId(1273294),
            name = "Delhi",
            country = CountryCode("IN"),
            admin1 = "Delhi",
            coordinates = Coordinates(28.6520, 77.2315),
            timeZone = TimeZone.of("Asia/Kolkata"),
        ),
        City(
            id = CityId(1283240),
            name = "Kathmandu",
            country = CountryCode("NP"),
            admin1 = "Bagmati Province",
            coordinates = Coordinates(27.7017, 85.3206),
            timeZone = TimeZone.of("Asia/Kathmandu"),
        ),
        City(
            id = CityId(1185241),
            name = "Dhaka",
            country = CountryCode("BD"),
            admin1 = "Dhaka Division",
            coordinates = Coordinates(23.7104, 90.4074),
            timeZone = TimeZone.of("Asia/Dhaka"),
        ),
        City(
            id = CityId(1298824),
            name = "Yangon",
            country = CountryCode("MM"),
            admin1 = "Yangon",
            coordinates = Coordinates(16.8053, 96.1561),
            timeZone = TimeZone.of("Asia/Yangon"),
        ),
        City(
            id = CityId(1642911),
            name = "Jakarta",
            country = CountryCode("ID"),
            admin1 = "Jakarta",
            coordinates = Coordinates(-6.2146, 106.8451),
            timeZone = TimeZone.of("Asia/Jakarta"),
        ),
        City(
            id = CityId(1880252),
            name = "Singapore",
            country = CountryCode("SG"),
            admin1 = "",
            coordinates = Coordinates(1.2897, 103.8501),
            timeZone = TimeZone.of("Asia/Singapore"),
        ),
        City(
            id = CityId(1850147),
            name = "Tokyo",
            country = CountryCode("JP"),
            admin1 = "Tokyo",
            coordinates = Coordinates(35.6895, 139.6917),
            timeZone = TimeZone.of("Asia/Tokyo"),
        ),
        City(
            id = CityId(2073124),
            name = "Darwin",
            country = CountryCode("AU"),
            admin1 = "Northern Territory",
            coordinates = Coordinates(-12.4611, 130.8418),
            timeZone = TimeZone.of("Australia/Darwin"),
        ),
        City(
            id = CityId(2147714),
            name = "Sydney",
            country = CountryCode("AU"),
            admin1 = "New South Wales",
            coordinates = Coordinates(-33.8678, 151.2073),
            timeZone = TimeZone.of("Australia/Sydney"),
        ),
        City(
            id = CityId(2139521),
            name = "Nouméa",
            country = CountryCode("NC"),
            admin1 = "South Province",
            coordinates = Coordinates(-22.2741, 166.4488),
            timeZone = TimeZone.of("Pacific/Noumea"),
        ),
        City(
            id = CityId(2193733),
            name = "Auckland",
            country = CountryCode("NZ"),
            admin1 = "Auckland",
            coordinates = Coordinates(-36.8485, 174.7635),
            timeZone = TimeZone.of("Pacific/Auckland"),
        ),
        City(
            id = CityId(4032402),
            name = "Nuku'alofa",
            country = CountryCode("TO"),
            admin1 = "Tongatapu",
            coordinates = Coordinates(-21.1368, -175.2011),
            timeZone = TimeZone.of("Pacific/Tongatapu"),
        ),
        City(
            id = CityId(109223),
            name = "Madinah",
            country = CountryCode("SA"),
            admin1 = "Medina Region",
            coordinates = Coordinates(24.4686, 39.6142),
            timeZone = TimeZone.of("Asia/Riyadh"),
            arabicName = "المدينة المنورة",
        ),
        City(
            id = CityId(108410),
            name = "Riyadh",
            country = CountryCode("SA"),
            admin1 = "Riyadh Region",
            coordinates = Coordinates(24.6877, 46.7219),
            timeZone = TimeZone.of("Asia/Riyadh"),
            arabicName = "الرياض",
        ),
        City(
            id = CityId(7303419),
            name = "East Jerusalem",
            country = CountryCode("PS"),
            admin1 = "West Bank",
            coordinates = Coordinates(31.7834, 35.2339),
            timeZone = TimeZone.of("Asia/Hebron"),
            arabicName = "القدس الشرقية",
        ),
        City(
            id = CityId(71137),
            name = "Sanaa",
            country = CountryCode("YE"),
            admin1 = "Amanat Alasimah",
            coordinates = Coordinates(15.3545, 44.2065),
            timeZone = TimeZone.of("Asia/Aden"),
            arabicName = "صنعاء",
        ),
        City(
            id = CityId(415189),
            name = "Aden",
            country = CountryCode("YE"),
            admin1 = "Aden",
            coordinates = Coordinates(12.7796, 45.0385),
            timeZone = TimeZone.of("Asia/Aden"),
            arabicName = "عدن",
        ),
        City(
            id = CityId(250441),
            name = "Amman",
            country = CountryCode("JO"),
            admin1 = "Amman",
            coordinates = Coordinates(31.9552, 35.9450),
            timeZone = TimeZone.of("Asia/Amman"),
            arabicName = "عمّان",
        ),
        City(
            id = CityId(361058),
            name = "Alexandria",
            country = CountryCode("EG"),
            admin1 = "Alexandria",
            coordinates = Coordinates(31.2018, 29.9158),
            timeZone = TimeZone.of("Africa/Cairo"),
            arabicName = "الإسكندرية",
        ),
        City(
            id = CityId(98182),
            name = "Baghdad",
            country = CountryCode("IQ"),
            admin1 = "Baghdad",
            coordinates = Coordinates(33.3406, 44.4009),
            timeZone = TimeZone.of("Asia/Baghdad"),
            arabicName = "بغداد",
        ),
        City(
            id = CityId(170654),
            name = "Damascus",
            country = CountryCode("SY"),
            admin1 = "Damascus Governorate",
            coordinates = Coordinates(33.5102, 36.2913),
            timeZone = TimeZone.of("Asia/Damascus"),
            arabicName = "دمشق",
        ),
        City(
            id = CityId(276781),
            name = "Beirut",
            country = CountryCode("LB"),
            admin1 = "Beirut",
            coordinates = Coordinates(33.8933, 35.5016),
            timeZone = TimeZone.of("Asia/Beirut"),
            arabicName = "بيروت",
        ),
        City(
            id = CityId(285787),
            name = "Kuwait City",
            country = CountryCode("KW"),
            admin1 = "Al Asimah",
            coordinates = Coordinates(29.3670, 47.9743),
            timeZone = TimeZone.of("Asia/Kuwait"),
            arabicName = "الكويت",
        ),
        City(
            id = CityId(290030),
            name = "Doha",
            country = CountryCode("QA"),
            admin1 = "Baladiyat ad Dawhah",
            coordinates = Coordinates(25.2854, 51.5310),
            timeZone = TimeZone.of("Asia/Qatar"),
            arabicName = "الدوحة",
        ),
        City(
            id = CityId(287286),
            name = "Muscat",
            country = CountryCode("OM"),
            admin1 = "Muscat",
            coordinates = Coordinates(23.5841, 58.4078),
            timeZone = TimeZone.of("Asia/Muscat"),
            arabicName = "مسقط",
        ),
        City(
            id = CityId(290340),
            name = "Manama",
            country = CountryCode("BH"),
            admin1 = "Manama",
            coordinates = Coordinates(26.2279, 50.5856),
            timeZone = TimeZone.of("Asia/Bahrain"),
            arabicName = "المنامة",
        ),
        City(
            id = CityId(745044),
            name = "Istanbul",
            country = CountryCode("TR"),
            admin1 = "Istanbul",
            coordinates = Coordinates(41.0138, 28.9497),
            timeZone = TimeZone.of("Europe/Istanbul"),
            arabicName = "إسطنبول",
        ),
        City(
            id = CityId(323786),
            name = "Ankara",
            country = CountryCode("TR"),
            admin1 = "Ankara",
            coordinates = Coordinates(39.9199, 32.8543),
            timeZone = TimeZone.of("Europe/Istanbul"),
            arabicName = "أنقرة",
        ),
        City(
            id = CityId(2553604),
            name = "Casablanca",
            country = CountryCode("MA"),
            admin1 = "Casablanca-Settat",
            coordinates = Coordinates(33.5883, -7.6114),
            timeZone = TimeZone.of("Africa/Casablanca"),
            arabicName = "الدار البيضاء",
        ),
        City(
            id = CityId(2538475),
            name = "Rabat",
            country = CountryCode("MA"),
            admin1 = "Rabat-Salé-Kénitra",
            coordinates = Coordinates(34.0132, -6.8326),
            timeZone = TimeZone.of("Africa/Casablanca"),
            arabicName = "الرباط",
        ),
        City(
            id = CityId(2507480),
            name = "Algiers",
            country = CountryCode("DZ"),
            admin1 = "Algiers",
            coordinates = Coordinates(36.7322, 3.0875),
            timeZone = TimeZone.of("Africa/Algiers"),
            arabicName = "الجزائر",
        ),
        City(
            id = CityId(2464470),
            name = "Tunis",
            country = CountryCode("TN"),
            admin1 = "Tunis Governorate",
            coordinates = Coordinates(36.8190, 10.1658),
            timeZone = TimeZone.of("Africa/Tunis"),
            arabicName = "تونس",
        ),
        City(
            id = CityId(2210247),
            name = "Tripoli",
            country = CountryCode("LY"),
            admin1 = "Tripoli",
            coordinates = Coordinates(32.8874, 13.1873),
            timeZone = TimeZone.of("Africa/Tripoli"),
            arabicName = "طرابلس",
        ),
        City(
            id = CityId(379252),
            name = "Khartoum",
            country = CountryCode("SD"),
            admin1 = "Khartoum",
            coordinates = Coordinates(15.5518, 32.5324),
            timeZone = TimeZone.of("Africa/Khartoum"),
            arabicName = "الخرطوم",
        ),
        City(
            id = CityId(53654),
            name = "Mogadishu",
            country = CountryCode("SO"),
            admin1 = "Banaadir",
            coordinates = Coordinates(2.0371, 45.3438),
            timeZone = TimeZone.of("Africa/Mogadishu"),
            arabicName = "مقديشو",
        ),
        City(
            id = CityId(1735161),
            name = "Kuala Lumpur",
            country = CountryCode("MY"),
            admin1 = "Kuala Lumpur",
            coordinates = Coordinates(3.1412, 101.6865),
            timeZone = TimeZone.of("Asia/Kuala_Lumpur"),
            arabicName = "كوالالمبور",
        ),
        City(
            id = CityId(1176615),
            name = "Islamabad",
            country = CountryCode("PK"),
            admin1 = "Islamabad",
            coordinates = Coordinates(33.7215, 73.0433),
            timeZone = TimeZone.of("Asia/Karachi"),
            arabicName = "إسلام آباد",
        ),
        City(
            id = CityId(1172451),
            name = "Lahore",
            country = CountryCode("PK"),
            admin1 = "Punjab",
            coordinates = Coordinates(31.5580, 74.3507),
            timeZone = TimeZone.of("Asia/Karachi"),
            arabicName = "لاهور",
        ),
        City(
            id = CityId(1512569),
            name = "Tashkent",
            country = CountryCode("UZ"),
            admin1 = "Tashkent",
            coordinates = Coordinates(41.2647, 69.2163),
            timeZone = TimeZone.of("Asia/Tashkent"),
            arabicName = "طشقند",
        ),
        City(
            id = CityId(587084),
            name = "Baku",
            country = CountryCode("AZ"),
            admin1 = "Baki",
            coordinates = Coordinates(40.3777, 49.8920),
            timeZone = TimeZone.of("Asia/Baku"),
            arabicName = "باكو",
        ),
        City(
            id = CityId(2988507),
            name = "Paris",
            country = CountryCode("FR"),
            admin1 = "Île-de-France",
            coordinates = Coordinates(48.8534, 2.3488),
            timeZone = TimeZone.of("Europe/Paris"),
            arabicName = "باريس",
        ),
        City(
            id = CityId(2950159),
            name = "Berlin",
            country = CountryCode("DE"),
            admin1 = "State of Berlin",
            coordinates = Coordinates(52.5244, 13.4105),
            timeZone = TimeZone.of("Europe/Berlin"),
            arabicName = "برلين",
        ),
        City(
            id = CityId(6167865),
            name = "Toronto",
            country = CountryCode("CA"),
            admin1 = "Ontario",
            coordinates = Coordinates(43.7064, -79.3986),
            timeZone = TimeZone.of("America/Toronto"),
            arabicName = "تورونتو",
        ),
        City(
            id = CityId(2649808),
            name = "Exeter",
            country = CountryCode("GB"),
            admin1 = "England",
            coordinates = Coordinates(50.7236, -3.5275),
            timeZone = TimeZone.of("Europe/London"),
            arabicName = "إكستر",
        ),
        City(
            id = CityId(2655603),
            name = "Birmingham",
            country = CountryCode("GB"),
            admin1 = "England",
            coordinates = Coordinates(52.4814, -1.8998),
            timeZone = TimeZone.of("Europe/London"),
            arabicName = "برمنغهام",
        ),
    )
