package app.saadiah.model

import kotlinx.datetime.TimeZone

/**
 * Curated list of prominent cities spanning every standard timezone offset from UTC-10 to UTC+13.
 * These provide quick zero-keystroke selection and serve as global benchmark targets.
 */
val EXTENDED_CITIES: List<City> =
    listOf(
        City(
            id = CityId(5856195),
            name = "Honolulu",
            country = CountryCode("US"),
            admin1 = "Hawaii",
            coordinates = Coordinates(21.3069, -157.8583),
            timeZone = TimeZone.of("Pacific/Honolulu"),
        ),
        City(
            id = CityId(5879400),
            name = "Anchorage",
            country = CountryCode("US"),
            admin1 = "Alaska",
            coordinates = Coordinates(61.2181, -149.9003),
            timeZone = TimeZone.of("America/Anchorage"),
        ),
        City(
            id = CityId(5368361),
            name = "Los Angeles",
            country = CountryCode("US"),
            admin1 = "California",
            coordinates = Coordinates(34.0522, -118.2437),
            timeZone = TimeZone.of("America/Los_Angeles"),
        ),
        City(
            id = CityId(5419384),
            name = "Denver",
            country = CountryCode("US"),
            admin1 = "Colorado",
            coordinates = Coordinates(39.7392, -104.9847),
            timeZone = TimeZone.of("America/Denver"),
        ),
        City(
            id = CityId(4887398),
            name = "Chicago",
            country = CountryCode("US"),
            admin1 = "Illinois",
            coordinates = Coordinates(41.8500, -87.6500),
            timeZone = TimeZone.of("America/Chicago"),
        ),
        City(
            id = CityId(5128581),
            name = "New York City",
            country = CountryCode("US"),
            admin1 = "New York",
            coordinates = Coordinates(40.7143, -74.0060),
            timeZone = TimeZone.of("America/New_York"),
        ),
        City(
            id = CityId(6324729),
            name = "Halifax",
            country = CountryCode("CA"),
            admin1 = "Nova Scotia",
            coordinates = Coordinates(44.6427, -63.5769),
            timeZone = TimeZone.of("America/Halifax"),
        ),
        City(
            id = CityId(3448439),
            name = "São Paulo",
            country = CountryCode("BR"),
            admin1 = "São Paulo",
            coordinates = Coordinates(-23.5475, -46.6361),
            timeZone = TimeZone.of("America/Sao_Paulo"),
        ),
        City(
            id = CityId(3385075),
            name = "Fernando de Noronha",
            country = CountryCode("BR"),
            admin1 = "Pernambuco",
            coordinates = Coordinates(-3.8546, -32.4277),
            timeZone = TimeZone.of("America/Noronha"),
        ),
        City(
            id = CityId(3374333),
            name = "Praia",
            country = CountryCode("CV"),
            admin1 = "Praia",
            coordinates = Coordinates(14.9315, -23.5125),
            timeZone = TimeZone.of("Atlantic/Cape_Verde"),
        ),
        City(
            id = CityId(2253354),
            name = "Dakar",
            country = CountryCode("SN"),
            admin1 = "Dakar",
            coordinates = Coordinates(14.6937, -17.4441),
            timeZone = TimeZone.of("Africa/Dakar"),
        ),
        City(
            id = CityId(2643743),
            name = "London",
            country = CountryCode("GB"),
            admin1 = "England",
            coordinates = Coordinates(51.5085, -0.1257),
            timeZone = TimeZone.of("Europe/London"),
        ),
        City(
            id = CityId(2332459),
            name = "Lagos",
            country = CountryCode("NG"),
            admin1 = "Lagos",
            coordinates = Coordinates(6.4541, 3.3947),
            timeZone = TimeZone.of("Africa/Lagos"),
        ),
        City(
            id = CityId(360630),
            name = "Cairo",
            country = CountryCode("EG"),
            admin1 = "Cairo",
            coordinates = Coordinates(30.0626, 31.2497),
            timeZone = TimeZone.of("Africa/Cairo"),
        ),
        City(
            id = CityId(993800),
            name = "Johannesburg",
            country = CountryCode("ZA"),
            admin1 = "Gauteng",
            coordinates = Coordinates(-26.2023, 28.0436),
            timeZone = TimeZone.of("Africa/Johannesburg"),
        ),
        City(
            id = CityId(104515),
            name = "Makkah",
            country = CountryCode("SA"),
            admin1 = "Mecca Region",
            coordinates = Coordinates(21.42664, 39.82563),
            timeZone = TimeZone.of("Asia/Riyadh"),
            arabicName = "مكة المكرمة",
        ),
        City(
            id = CityId(112931),
            name = "Tehran",
            country = CountryCode("IR"),
            admin1 = "Tehran",
            coordinates = Coordinates(35.6944, 51.4215),
            timeZone = TimeZone.of("Asia/Tehran"),
        ),
        City(
            id = CityId(292223),
            name = "Dubai",
            country = CountryCode("AE"),
            admin1 = "Dubai",
            coordinates = Coordinates(25.0772, 55.3093),
            timeZone = TimeZone.of("Asia/Dubai"),
        ),
        City(
            id = CityId(1138958),
            name = "Kabul",
            country = CountryCode("AF"),
            admin1 = "Kabul",
            coordinates = Coordinates(34.5281, 69.1723),
            timeZone = TimeZone.of("Asia/Kabul"),
        ),
        City(
            id = CityId(1174872),
            name = "Karachi",
            country = CountryCode("PK"),
            admin1 = "Sindh",
            coordinates = Coordinates(24.8608, 67.0104),
            timeZone = TimeZone.of("Asia/Karachi"),
        ),
        City(
            id = CityId(1273294),
            name = "Delhi",
            country = CountryCode("IN"),
            admin1 = "Delhi",
            coordinates = Coordinates(28.6520, 77.2315),
            timeZone = TimeZone.of("Asia/Kolkata"),
        ),
        City(
            id = CityId(1283240),
            name = "Kathmandu",
            country = CountryCode("NP"),
            admin1 = "Bagmati Province",
            coordinates = Coordinates(27.7017, 85.3206),
            timeZone = TimeZone.of("Asia/Kathmandu"),
        ),
        City(
            id = CityId(1185241),
            name = "Dhaka",
            country = CountryCode("BD"),
            admin1 = "Dhaka Division",
            coordinates = Coordinates(23.7104, 90.4074),
            timeZone = TimeZone.of("Asia/Dhaka"),
        ),
        City(
            id = CityId(1298824),
            name = "Yangon",
            country = CountryCode("MM"),
            admin1 = "Yangon",
            coordinates = Coordinates(16.8053, 96.1561),
            timeZone = TimeZone.of("Asia/Yangon"),
        ),
        City(
            id = CityId(1642911),
            name = "Jakarta",
            country = CountryCode("ID"),
            admin1 = "Jakarta",
            coordinates = Coordinates(-6.2146, 106.8451),
            timeZone = TimeZone.of("Asia/Jakarta"),
        ),
        City(
            id = CityId(1880252),
            name = "Singapore",
            country = CountryCode("SG"),
            admin1 = "",
            coordinates = Coordinates(1.2897, 103.8501),
            timeZone = TimeZone.of("Asia/Singapore"),
        ),
        City(
            id = CityId(1850147),
            name = "Tokyo",
            country = CountryCode("JP"),
            admin1 = "Tokyo",
            coordinates = Coordinates(35.6895, 139.6917),
            timeZone = TimeZone.of("Asia/Tokyo"),
        ),
        City(
            id = CityId(2073124),
            name = "Darwin",
            country = CountryCode("AU"),
            admin1 = "Northern Territory",
            coordinates = Coordinates(-12.4611, 130.8418),
            timeZone = TimeZone.of("Australia/Darwin"),
        ),
        City(
            id = CityId(2147714),
            name = "Sydney",
            country = CountryCode("AU"),
            admin1 = "New South Wales",
            coordinates = Coordinates(-33.8678, 151.2073),
            timeZone = TimeZone.of("Australia/Sydney"),
        ),
        City(
            id = CityId(2139521),
            name = "Nouméa",
            country = CountryCode("NC"),
            admin1 = "South Province",
            coordinates = Coordinates(-22.2741, 166.4488),
            timeZone = TimeZone.of("Pacific/Noumea"),
        ),
        City(
            id = CityId(2193733),
            name = "Auckland",
            country = CountryCode("NZ"),
            admin1 = "Auckland",
            coordinates = Coordinates(-36.8485, 174.7635),
            timeZone = TimeZone.of("Pacific/Auckland"),
        ),
        City(
            id = CityId(4032402),
            name = "Nuku'alofa",
            country = CountryCode("TO"),
            admin1 = "Tongatapu",
            coordinates = Coordinates(-21.1368, -175.2011),
            timeZone = TimeZone.of("Pacific/Tongatapu"),
        ),
    )
