package app.saadiah.ui

data class SurahInfo(
    val number: Int,
    val arabicName: String,
    val englishName: String,
    val ayahCount: Int,
    val isMadani: Boolean,
    val isBundled: Boolean,
)

object SurahCatalog {
    val surahs: List<SurahInfo> =
        listOf(
            SurahInfo(1, "الفاتحة", "Al-Fatihah", 7, isMadani = false, isBundled = false),
            SurahInfo(2, "البقرة", "Al-Baqarah", 286, isMadani = true, isBundled = true),
            SurahInfo(3, "آل عمران", "Aal 'Imran", 200, isMadani = true, isBundled = true),
            SurahInfo(4, "النساء", "An-Nisa", 176, isMadani = true, isBundled = false),
            SurahInfo(5, "المائدة", "Al-Ma'idah", 120, isMadani = true, isBundled = false),
            SurahInfo(6, "الأنعام", "Al-An'am", 165, isMadani = false, isBundled = false),
            SurahInfo(7, "الأعراف", "Al-A'raf", 206, isMadani = false, isBundled = false),
            SurahInfo(8, "الأنفال", "Al-Anfal", 75, isMadani = true, isBundled = false),
            SurahInfo(9, "التوبة", "At-Tawbah", 129, isMadani = true, isBundled = false),
            SurahInfo(10, "يونس", "Yunus", 109, isMadani = false, isBundled = false),
            SurahInfo(11, "هود", "Hud", 123, isMadani = false, isBundled = false),
            SurahInfo(12, "يوسف", "Yusuf", 111, isMadani = false, isBundled = false),
            SurahInfo(13, "الرعد", "Ar-Ra'd", 43, isMadani = true, isBundled = false),
            SurahInfo(14, "إبراهيم", "Ibrahim", 52, isMadani = false, isBundled = false),
            SurahInfo(15, "الحجر", "Al-Hijr", 99, isMadani = false, isBundled = false),
            SurahInfo(16, "النحل", "An-Nahl", 128, isMadani = false, isBundled = false),
            SurahInfo(17, "الإسراء", "Al-Isra", 111, isMadani = false, isBundled = false),
            SurahInfo(18, "الكهف", "Al-Kahf", 110, isMadani = false, isBundled = false),
            SurahInfo(19, "مريم", "Maryam", 98, isMadani = false, isBundled = false),
            SurahInfo(20, "طه", "Taha", 135, isMadani = false, isBundled = false),
            SurahInfo(21, "الأنبياء", "Al-Anbiya", 112, isMadani = false, isBundled = false),
            SurahInfo(22, "الحج", "Al-Hajj", 78, isMadani = true, isBundled = false),
            SurahInfo(23, "المؤمنون", "Al-Mu'minun", 118, isMadani = false, isBundled = false),
            SurahInfo(24, "النور", "An-Nur", 64, isMadani = true, isBundled = false),
            SurahInfo(25, "الفرقان", "Al-Furqan", 77, isMadani = false, isBundled = false),
            SurahInfo(26, "الشعراء", "Ash-Shu'ara", 227, isMadani = false, isBundled = false),
            SurahInfo(27, "النمل", "An-Naml", 93, isMadani = false, isBundled = false),
            SurahInfo(28, "القصص", "Al-Qasas", 88, isMadani = false, isBundled = false),
            SurahInfo(29, "العنكبوت", "Al-'Ankabut", 69, isMadani = false, isBundled = false),
            SurahInfo(30, "الروم", "Ar-Rum", 60, isMadani = false, isBundled = false),
            SurahInfo(31, "لقمان", "Luqman", 34, isMadani = false, isBundled = false),
            SurahInfo(32, "السجدة", "As-Sajdah", 30, isMadani = false, isBundled = false),
            SurahInfo(33, "الأحزاب", "Al-Ahzab", 73, isMadani = true, isBundled = false),
            SurahInfo(34, "سبأ", "Saba", 54, isMadani = false, isBundled = false),
            SurahInfo(35, "فاطر", "Fatir", 45, isMadani = false, isBundled = false),
            SurahInfo(36, "يس", "Ya-Sin", 83, isMadani = false, isBundled = false),
            SurahInfo(37, "الصافات", "As-Saffat", 182, isMadani = false, isBundled = false),
            SurahInfo(38, "ص", "Sad", 88, isMadani = false, isBundled = false),
            SurahInfo(39, "الزمر", "Az-Zumar", 75, isMadani = false, isBundled = false),
            SurahInfo(40, "غافر", "Ghafir", 85, isMadani = false, isBundled = false),
            SurahInfo(41, "فصلت", "Fussilat", 54, isMadani = false, isBundled = false),
            SurahInfo(42, "الشورى", "Ash-Shura", 53, isMadani = false, isBundled = false),
            SurahInfo(43, "الزخرف", "Az-Zukhruf", 89, isMadani = false, isBundled = false),
            SurahInfo(44, "الدخان", "Ad-Dukhan", 59, isMadani = false, isBundled = false),
            SurahInfo(45, "الجاثية", "Al-Jathiyah", 37, isMadani = false, isBundled = false),
            SurahInfo(46, "الأحقاف", "Al-Ahqaf", 35, isMadani = false, isBundled = false),
            SurahInfo(47, "محمد", "Muhammad", 38, isMadani = true, isBundled = false),
            SurahInfo(48, "الفتح", "Al-Fath", 29, isMadani = true, isBundled = false),
            SurahInfo(49, "الحجرات", "Al-Hujurat", 18, isMadani = true, isBundled = false),
            SurahInfo(50, "ق", "Qaf", 45, isMadani = false, isBundled = false),
            SurahInfo(51, "الذاريات", "Adh-Dhariyat", 60, isMadani = false, isBundled = false),
            SurahInfo(52, "الطور", "At-Tur", 49, isMadani = false, isBundled = false),
            SurahInfo(53, "النجم", "An-Najm", 62, isMadani = false, isBundled = false),
            SurahInfo(54, "القمر", "Al-Qamar", 55, isMadani = false, isBundled = false),
            SurahInfo(55, "الرحمن", "Ar-Rahman", 78, isMadani = true, isBundled = false),
            SurahInfo(56, "الواقعة", "Al-Waqi'ah", 96, isMadani = false, isBundled = false),
            SurahInfo(57, "الحديد", "Al-Hadid", 29, isMadani = true, isBundled = false),
            SurahInfo(58, "المجادلة", "Al-Mujadila", 22, isMadani = true, isBundled = false),
            SurahInfo(59, "الحشر", "Al-Hashr", 24, isMadani = true, isBundled = false),
            SurahInfo(60, "الممتحنة", "Al-Mumtahanah", 13, isMadani = true, isBundled = false),
            SurahInfo(61, "الصف", "As-Saff", 14, isMadani = true, isBundled = false),
            SurahInfo(62, "الجمعة", "Al-Jumu'ah", 11, isMadani = true, isBundled = false),
            SurahInfo(63, "المنافقون", "Al-Munafiqun", 11, isMadani = true, isBundled = false),
            SurahInfo(64, "التغابن", "At-Taghabun", 18, isMadani = true, isBundled = false),
            SurahInfo(65, "الطلاق", "At-Talaq", 12, isMadani = true, isBundled = false),
            SurahInfo(66, "التحريم", "At-Tahrim", 12, isMadani = true, isBundled = false),
            SurahInfo(67, "الملك", "Al-Mulk", 30, isMadani = false, isBundled = false),
            SurahInfo(68, "القلم", "Al-Qalam", 52, isMadani = false, isBundled = false),
            SurahInfo(69, "الحاقة", "Al-Haqqah", 52, isMadani = false, isBundled = false),
            SurahInfo(70, "المعارج", "Al-Ma'arij", 44, isMadani = false, isBundled = false),
            SurahInfo(71, "نوح", "Nuh", 28, isMadani = false, isBundled = false),
            SurahInfo(72, "الجن", "Al-Jinn", 28, isMadani = false, isBundled = false),
            SurahInfo(73, "المزمل", "Al-Muzzammil", 20, isMadani = false, isBundled = false),
            SurahInfo(74, "المدثر", "Al-Muddaththir", 56, isMadani = false, isBundled = false),
            SurahInfo(75, "القيامة", "Al-Qiyamah", 40, isMadani = false, isBundled = false),
            SurahInfo(76, "الإنسان", "Al-Insan", 31, isMadani = true, isBundled = false),
            SurahInfo(77, "المرسلات", "Al-Mursalat", 50, isMadani = false, isBundled = false),
            SurahInfo(78, "النبأ", "An-Naba", 40, isMadani = false, isBundled = false),
            SurahInfo(79, "النازعات", "An-Nazi'at", 46, isMadani = false, isBundled = false),
            SurahInfo(80, "عبس", "'Abasa", 42, isMadani = false, isBundled = false),
            SurahInfo(81, "التكوير", "At-Takwir", 29, isMadani = false, isBundled = false),
            SurahInfo(82, "الانفطار", "Al-Infitar", 19, isMadani = false, isBundled = false),
            SurahInfo(83, "المطففين", "Al-Mutaffifin", 36, isMadani = false, isBundled = false),
            SurahInfo(84, "الانشقاق", "Al-Inshiqaq", 25, isMadani = false, isBundled = false),
            SurahInfo(85, "البروج", "Al-Buruj", 22, isMadani = false, isBundled = false),
            SurahInfo(86, "الطارق", "At-Tariq", 17, isMadani = false, isBundled = false),
            SurahInfo(87, "الأعلى", "Al-A'la", 19, isMadani = false, isBundled = false),
            SurahInfo(88, "الغاشية", "Al-Ghashiyah", 26, isMadani = false, isBundled = false),
            SurahInfo(89, "الفجر", "Al-Fajr", 30, isMadani = false, isBundled = false),
            SurahInfo(90, "البلد", "Al-Balad", 20, isMadani = false, isBundled = false),
            SurahInfo(91, "الشمس", "Ash-Shams", 15, isMadani = false, isBundled = false),
            SurahInfo(92, "الليل", "Al-Layl", 21, isMadani = false, isBundled = false),
            SurahInfo(93, "الضحى", "Ad-Duha", 11, isMadani = false, isBundled = false),
            SurahInfo(94, "الشرح", "Ash-Sharh", 8, isMadani = false, isBundled = false),
            SurahInfo(95, "التين", "At-Tin", 8, isMadani = false, isBundled = false),
            SurahInfo(96, "العلق", "Al-'Alaq", 19, isMadani = false, isBundled = false),
            SurahInfo(97, "القدر", "Al-Qadr", 5, isMadani = false, isBundled = false),
            SurahInfo(98, "البينة", "Al-Bayyinah", 8, isMadani = true, isBundled = false),
            SurahInfo(99, "الزلزلة", "Az-Zalzalah", 8, isMadani = true, isBundled = false),
            SurahInfo(100, "العاديات", "Al-'Adiyat", 11, isMadani = false, isBundled = false),
            SurahInfo(101, "القارعة", "Al-Qari'ah", 11, isMadani = false, isBundled = false),
            SurahInfo(102, "التكاثر", "At-Takathur", 8, isMadani = false, isBundled = false),
            SurahInfo(103, "العصر", "Al-'Asr", 3, isMadani = false, isBundled = false),
            SurahInfo(104, "الهمزة", "Al-Humazah", 9, isMadani = false, isBundled = false),
            SurahInfo(105, "الفيل", "Al-Fil", 5, isMadani = false, isBundled = false),
            SurahInfo(106, "قريش", "Quraysh", 4, isMadani = false, isBundled = false),
            SurahInfo(107, "الماعون", "Al-Ma'un", 7, isMadani = false, isBundled = false),
            SurahInfo(108, "الكوثر", "Al-Kawthar", 3, isMadani = false, isBundled = false),
            SurahInfo(109, "الكافرون", "Al-Kafirun", 6, isMadani = false, isBundled = false),
            SurahInfo(110, "النصر", "An-Nasr", 3, isMadani = true, isBundled = false),
            SurahInfo(111, "المسد", "Al-Masad", 5, isMadani = false, isBundled = false),
            SurahInfo(112, "الإخلاص", "Al-Ikhlas", 4, isMadani = false, isBundled = false),
            SurahInfo(113, "الفلق", "Al-Falaq", 5, isMadani = false, isBundled = false),
            SurahInfo(114, "الناس", "An-Nas", 6, isMadani = false, isBundled = false),
        )

    fun forNumber(number: Int): SurahInfo = surahs.getOrNull(number - 1) ?: surahs[1]
}
