#!/usr/bin/env python3
"""Generate the committed Umm al-Qura month-length table.

Run manually; never invoked by Gradle. Downloads nothing — point it at a local
copy of the source whose checksum matches docs/data-provenance.md.

    python tools/gen-hijri-table.py path/to/islamcal.cpp > \
        core/calendar/src/commonMain/kotlin/app/saadiah/calendar/UmmAlQuraTable.kt

Source data: ICU4C icu4c/source/i18n/islamcal.cpp (UMALQURA_MONTHLENGTH and
umAlQuraYrStartEstimateFix), covering 1300-1600 AH. ICU derives it from the
published Umm al-Qura calendar. See docs/data-provenance.md.

The script validates the source before emitting: for every year it checks that
the accumulated month lengths reach the next year's start day, so the two ICU
arrays corroborate each other rather than being trusted blindly.
"""

import hashlib
import re
import sys

FIRST_YEAR = 1356
LAST_YEAR = 1500

ICU_FIRST_YEAR = 1300
JDN_OF_UNIX_EPOCH = 2440588
CIVIL_EPOC = 1948440


def parse_icu(source):
    # ICU closes UMALQURA_MONTHLENGTH with a '};' that sits inside a '//'
    # comment, so line comments must go before the array is located.
    clean = re.sub(r"//[^\n]*", "", source)

    def block(name):
        start = clean.index(name)
        open_brace = clean.index("{", start)
        return clean[open_brace + 1 : clean.index("};", open_brace)]

    months = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]+)", block("UMALQURA_MONTHLENGTH[]"))]
    fixes = [int(x) for x in re.findall(r"-?\d+", block("umAlQuraYrStartEstimateFix[]"))]
    if len(months) != len(fixes):
        raise SystemExit(f"table size mismatch: {len(months)} month masks vs {len(fixes)} fixes")
    return months, fixes


def year_start(fixes, year):
    """Days from the Hijri epoch to 1 Muharram of `year`, per ICU."""
    index = year - ICU_FIRST_YEAR
    return int((354.36720 * index) + 460322.05 + 0.5) + fixes[index]


def month_length(months, year, month_index):
    mask = 0x01 << (11 - month_index)
    return 30 if months[year - ICU_FIRST_YEAR] & mask else 29


def validate(months, fixes):
    last = ICU_FIRST_YEAR + len(months) - 1
    for year in range(ICU_FIRST_YEAR, last):
        accumulated = year_start(fixes, year) + sum(month_length(months, year, m) for m in range(12))
        if accumulated != year_start(fixes, year + 1):
            raise SystemExit(f"inconsistent source data at {year} AH")


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    # .gitattributes forces LF; without this Python emits CRLF on Windows.
    sys.stdout.reconfigure(newline="\n")
    raw = open(sys.argv[1], "rb").read()
    print(f"source sha-256: {hashlib.sha256(raw).hexdigest()}", file=sys.stderr)
    months, fixes = parse_icu(raw.decode("utf-8", "replace"))
    validate(months, fixes)

    anchor = CIVIL_EPOC + year_start(fixes, FIRST_YEAR) - JDN_OF_UNIX_EPOCH
    masks = [months[y - ICU_FIRST_YEAR] for y in range(FIRST_YEAR, LAST_YEAR + 1)]

    # One entry per line, matching what spotless/ktlint produces, so that
    # regenerating reproduces the committed file byte for byte.
    rows = [f"        0x{m:03X}," for m in masks]

    print(f"""// Generated by tools/gen-hijri-table.py. Do not edit.
// Umm al-Qura month lengths for {FIRST_YEAR}-{LAST_YEAR} AH, twelve bits per year:
// bit (11 - monthIndex) set means that month has 30 days rather than 29.
package app.saadiah.calendar

internal const val UMM_AL_QURA_FIRST_YEAR = {FIRST_YEAR}
internal const val UMM_AL_QURA_LAST_YEAR = {LAST_YEAR}

// Epoch day of 1 Muharram {FIRST_YEAR} AH.
internal const val UMM_AL_QURA_ANCHOR_EPOCH_DAY = {anchor}

internal val UMM_AL_QURA_MONTH_LENGTHS =
    intArrayOf(
{chr(10).join(rows)}
    )""")


if __name__ == "__main__":
    sys.exit(main())
