#!/usr/bin/env python3
"""Generate the committed adhkār corpus.

Run manually; never invoked by Gradle. Downloads nothing — point it at local copies
whose checksums match docs/data-provenance.md.

    python tools/gen-adhkar-db.py path/to/ar.json path/to/en.json > \
        core/content/src/commonMain/kotlin/app/saadiah/content/generated/AdhkarCorpus.kt

Source: Seen-Arabic/Morning-And-Evening-Adhkar-DB (MIT). Arabic text, repetition counts,
virtue and hadith source come from ar.json; transliteration and translation from en.json,
joined on (type, order).

Swapping in a larger corpus means writing a new reader here and emitting the same
`Dhikr` shape. Nothing in the app changes: the schema is the contract, not this source.
Fields a future source may not carry are nullable — except `source`, which is required,
because DESIGN.md §6.4 refuses to render an entry without one.
"""

import hashlib
import json
import sys

# The dataset documents these: 0 is recited morning and evening, 1 morning, 2 evening.
BOTH, MORNING_ONLY, EVENING_ONLY = 0, 1, 2

COLLECTIONS = {
    BOTH: ("MORNING", "EVENING"),
    MORNING_ONLY: ("MORNING",),
    EVENING_ONLY: ("EVENING",),
}

# This compilation's hadith sourcing is Sunni. Tagging it for both traditions would
# present Sunni-framed content to a Twelver user as their own, which CLAUDE.md calls a
# content failure. A Twelver corpus is tagged separately when one is sourced.
TRADITIONS = ("SUNNI",)


def kotlin_string(value):
    if value is None:
        return "null"
    escaped = (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", " ")
        .strip()
    )
    return f'"{escaped}"'


def optional(value):
    text = (value or "").strip()
    return kotlin_string(text) if text else "null"


def read(path):
    raw = open(path, "rb").read()
    print(f"{path} sha-256: {hashlib.sha256(raw).hexdigest()}", file=sys.stderr)
    return json.loads(raw.decode("utf-8"))


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    # Arabic will not survive the console's default encoding on Windows.
    sys.stdout.reconfigure(encoding="utf-8", newline="\n")

    arabic = {(e["type"], e["order"]): e for e in read(sys.argv[1])}
    english = {(e["type"], e["order"]): e for e in read(sys.argv[2])}
    if set(arabic) != set(english):
        raise SystemExit("the two files do not describe the same entries")

    entries = []
    for key in sorted(arabic, key=lambda k: (k[0], k[1])):
        ar, en = arabic[key], english[key]
        kind, order = key
        source = (ar.get("source") or "").strip()
        if not source:
            raise SystemExit(f"entry {key} has no source; §6.4 will not render it")
        collections = " , ".join(f"DhikrCollection.{c}" for c in COLLECTIONS[kind]).replace(" , ", ", ")
        traditions = ", ".join(f"Tradition.{t}" for t in TRADITIONS)
        entries.append(
            "        Dhikr(\n"
            f"            id = {kotlin_string(f'{kind}-{order}')},\n"
            f"            order = {order},\n"
            f"            arabic = {kotlin_string(ar['content'])},\n"
            f"            transliteration = {optional(en.get('transliteration'))},\n"
            f"            translation = {optional(en.get('translation'))},\n"
            f"            repetitions = {int(ar.get('count') or 1)},\n"
            f"            repetitionsInWords = {optional(ar.get('count_description'))},\n"
            f"            virtue = {optional(ar.get('fadl'))},\n"
            f"            source = {kotlin_string(source)},\n"
            f"            collections = setOf({collections}),\n"
            f"            traditions = setOf({traditions}),\n"
            "        ),"
        )

    body = "\n".join(entries)
    print(
        "// Generated by tools/gen-adhkar-db.py. Do not edit.\n"
        "// Source: Seen-Arabic/Morning-And-Evening-Adhkar-DB, MIT. See docs/data-provenance.md.\n"
        "// Each field stays on one line: wrapping Arabic would corrupt it.\n"
        '@file:Suppress("MaxLineLength")\n'
        "\n"
        "package app.saadiah.content.generated\n"
        "\n"
        "import app.saadiah.content.Dhikr\n"
        "import app.saadiah.content.DhikrCollection\n"
        "import app.saadiah.model.Tradition\n"
        "\n"
        "internal val ADHKAR_CORPUS: List<Dhikr> =\n"
        "    listOf(\n"
        f"{body}\n"
        "    )"
    )


if __name__ == "__main__":
    sys.exit(main())
