@file:Suppress("ktlint:standard:max-line-length")

package app.saadiah.content

import app.saadiah.model.Tradition

internal val AFTER_PRAYER_CORPUS: List<Dhikr> =
    listOf(
        Dhikr(
            id = "ap-1",
            order = 1,
            arabic = "أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، اللَّهُمَّ أَنْتَ السَّلاَمُ وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالإِكْرَامِ",
            transliteration = "Astaghfirullāh, Astaghfirullāh, Astaghfirullāh. Allāhumma Antas-Salāmu wa minkas-salām, tabārakta yā Dhal-Jalāli wal-Ikrām.",
            translation = "I ask Allah for forgiveness (three times). O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of majesty and honor.",
            repetitions = 1,
            repetitionsInWords = "مَرَّةٌ وَاحِدَةٌ",
            virtue = "كان رسول الله ﷺ إذا انصرف من صلاته استغفر ثلاثا وقال: اللهم أنت السلام...",
            source = "صحيح مسلم، برقم 591",
            collections = setOf(DhikrCollection.AFTER_PRAYER),
            traditions = setOf(Tradition.SUNNI),
            audioFileName = "adhkar_ap_1.mp3",
        ),
        Dhikr(
            id = "ap-2",
            order = 2,
            arabic = "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لاَ مَانِعَ لِمَا أَعْطَيْتَ، وَلاَ مُعْطِيَ لِمَا مَنَعْتَ، وَلاَ يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ",
            transliteration = "Lā ilāha illallāhu waḥdahu lā sharīka lah, lahul-mulku wa lahul-ḥamdu wa Huwa 'alā kulli shay'in qadīr. Allāhumma lā māni'a limā a'ṭayta, wa lā mu'ṭiya limā mana'ta, wa lā yanfa'u dhal-jaddi minkal-jadd.",
            translation = "None has the right to be worshipped but Allah alone, Who has no partner. His is the dominion and His is the praise, and He is Able to do all things. O Allah, there is none who can withhold what You give, and none may give what You have withheld; and the wealth of the wealthy person will not benefit him against You.",
            repetitions = 1,
            repetitionsInWords = "مَرَّةٌ وَاحِدَةٌ",
            virtue = "كان النبي ﷺ يقول في دبر كل صلاة مكتوبة إذا سلم...",
            source = "صحيح البخاري، برقم 844، وصحيح مسلم، برقم 593",
            collections = setOf(DhikrCollection.AFTER_PRAYER),
            traditions = setOf(Tradition.SUNNI),
            audioFileName = "adhkar_ap_2.mp3",
        ),
        Dhikr(
            id = "ap-3",
            order = 3,
            arabic = "أَعُوذُ بِاللَّهِ مِنَ الشَّيطَانِ الرَّجِيمِ ﴿اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَوَاتِ وَالْأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾",
            transliteration = "Allāhu lā ilāha illā Huwal-Ḥayyul-Qayyūm, lā ta'khudhuhu sinatun wa lā nawm, lahu mā fis-samāwāti wa māfil-arḍ, man dhal-ladhī yashfa'u 'indahu illā bi'idhnih, ya'lamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bishay'im-min 'ilmihi illā bimā shā', wasi'a kursiyyuhus-samāwāti wal-arḍ, wa lā ya'ūduhu ḥifẓuhumā, wa Huwal-'Aliyyul-'Aẓīm.",
            translation = "Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth...",
            repetitions = 1,
            repetitionsInWords = "مَرَّةٌ وَاحِدَةٌ",
            virtue = "من قرأ آية الكرسي دبر كل صلاة مكتوبة لم يمنعه من دخول الجنة إلا أن يموت",
            source = "رواه النسائي في السنن الكبرى، برقم 9848، وصححه الألباني في صحيح الجامع، برقم 6464",
            collections = setOf(DhikrCollection.AFTER_PRAYER),
            traditions = setOf(Tradition.SUNNI),
            audioFileName = "adhkar_ap_3.mp3",
        ),
        Dhikr(
            id = "ap-4",
            order = 4,
            arabic = "سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَاللَّهُ أَكْبَرُ",
            transliteration = "Subḥānallāh (33x), Al-ḥamdulillāh (33x), Allāhu Akbar (33x).",
            translation = "Glory be to Allah (33 times), Praise be to Allah (33 times), Allah is the Greatest (33 times). Completed by reciting: La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer.",
            repetitions = 33,
            repetitionsInWords = "ثَلَاثٌ وَثَلَاثُونَ مَرَّةً",
            virtue = "من سبح الله في دبر كل صلاة ثلاثا وثلاثين، وحمد الله ثلاثا وثلاثين، وكبر الله ثلاثا وثلاثين، فتلك تسعة وتسعون، وقال تمام المائة: لا إله إلا الله وحده لا شريك له... غفرت خطاياه وإن كانت مثل زبد البحر",
            source = "صحيح مسلم، برقم 597",
            collections = setOf(DhikrCollection.AFTER_PRAYER),
            traditions = setOf(Tradition.SUNNI),
            audioFileName = "adhkar_ap_4.mp3",
        ),
        Dhikr(
            id = "ap-5",
            order = 5,
            arabic = "قُلْ هُوَ اللَّهُ أَحَدٌ ۝ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
            transliteration = "Qul Huwallāhu Aḥad, Qul A'ūdhu bi Rabbil-Falaq, Qul A'ūdhu bi Rabbin-Nās.",
            translation = "Surat Al-Ikhlas, Surat Al-Falaq, and Surat An-Nas (Recited after every prayer; three times after Fajr and Maghrib).",
            repetitions = 1,
            repetitionsInWords = "مَرَّةٌ وَاحِدَةٌ",
            virtue = "أمرني رسول الله ﷺ أن أقرأ بالمعوذات دبر كل صلاة",
            source = "أخرجه أبو داود، برقم 1523، والترمذي، برقم 2903، وصححه الألباني",
            collections = setOf(DhikrCollection.AFTER_PRAYER),
            traditions = setOf(Tradition.SUNNI),
            audioFileName = "adhkar_ap_5.mp3",
        ),
    )
